name: Execute tests

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  tests:
    name: PHP ${{ matrix.php }}, ${{ matrix.setup }} setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        setup: ['basic', 'lowest']
        php: ['7.1', '7.2', '7.3']
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master # Action page: <https://github.com/shivammathur/setup-php>
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer 'hirak/prestissimo' package
        run: composer global require hirak/prestissimo --update-no-dev

      - name: Install lowest Composer dependencies
        if: matrix.setup == 'lowest'
        run: composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest

      - name: Install basic Composer dependencies
        if: matrix.setup == 'basic'
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Show most important packages versions
        run: composer info | grep -e laravel/laravel -e phpunit/phpunit -e phpstan/phpstan

      - name: Execute tests
        run: composer test
